[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "dist/server"
  included_files = ["dist/server/**"]

[build.environment]
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
