/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenstraRouteImport } from './routes/renstra'
import { Route as IndexRouteImport } from './routes/index'

const RenstraRoute = RenstraRouteImport.update({
  id: '/renstra',
  path: '/renstra',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/renstra': typeof RenstraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/renstra': typeof RenstraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/renstra': typeof RenstraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/renstra'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/renstra'
  id: '__root__' | '/' | '/renstra'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RenstraRoute: typeof RenstraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renstra': {
      id: '/renstra'
      path: '/renstra'
      fullPath: '/renstra'
      preLoaderRoute: typeof RenstraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RenstraRoute: RenstraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
