/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenstraRouteImport } from './routes/renstra'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestTableRouteImport } from './routes/guest-table'
import { Route as GuestDashboardRouteImport } from './routes/guest-dashboard'
import { Route as AdminProgressRouteImport } from './routes/admin-progress'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RenstraRoute = RenstraRouteImport.update({
  id: '/renstra',
  path: '/renstra',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestTableRoute = GuestTableRouteImport.update({
  id: '/guest-table',
  path: '/guest-table',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestDashboardRoute = GuestDashboardRouteImport.update({
  id: '/guest-dashboard',
  path: '/guest-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgressRoute = AdminProgressRouteImport.update({
  id: '/admin-progress',
  path: '/admin-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-progress': typeof AdminProgressRoute
  '/guest-dashboard': typeof GuestDashboardRoute
  '/guest-table': typeof GuestTableRoute
  '/login': typeof LoginRoute
  '/renstra': typeof RenstraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-progress': typeof AdminProgressRoute
  '/guest-dashboard': typeof GuestDashboardRoute
  '/guest-table': typeof GuestTableRoute
  '/login': typeof LoginRoute
  '/renstra': typeof RenstraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-progress': typeof AdminProgressRoute
  '/guest-dashboard': typeof GuestDashboardRoute
  '/guest-table': typeof GuestTableRoute
  '/login': typeof LoginRoute
  '/renstra': typeof RenstraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-progress'
    | '/guest-dashboard'
    | '/guest-table'
    | '/login'
    | '/renstra'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-progress'
    | '/guest-dashboard'
    | '/guest-table'
    | '/login'
    | '/renstra'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-dashboard'
    | '/admin-progress'
    | '/guest-dashboard'
    | '/guest-table'
    | '/login'
    | '/renstra'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProgressRoute: typeof AdminProgressRoute
  GuestDashboardRoute: typeof GuestDashboardRoute
  GuestTableRoute: typeof GuestTableRoute
  LoginRoute: typeof LoginRoute
  RenstraRoute: typeof RenstraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renstra': {
      id: '/renstra'
      path: '/renstra'
      fullPath: '/renstra'
      preLoaderRoute: typeof RenstraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-table': {
      id: '/guest-table'
      path: '/guest-table'
      fullPath: '/guest-table'
      preLoaderRoute: typeof GuestTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-dashboard': {
      id: '/guest-dashboard'
      path: '/guest-dashboard'
      fullPath: '/guest-dashboard'
      preLoaderRoute: typeof GuestDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-progress': {
      id: '/admin-progress'
      path: '/admin-progress'
      fullPath: '/admin-progress'
      preLoaderRoute: typeof AdminProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProgressRoute: AdminProgressRoute,
  GuestDashboardRoute: GuestDashboardRoute,
  GuestTableRoute: GuestTableRoute,
  LoginRoute: LoginRoute,
  RenstraRoute: RenstraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
